name: On Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-versions:
    uses: ./.github/workflows/reusable-update-versions.yml
    secrets:
      token: ${{ secrets.BALEEN_MARKETPLACE_RELEASE_LOOKUP_TOKEN }}
